#!/bin/sh

# Wait for files to be changed starting on this directory
inotifywait -r -e modify -e move -e create -e delete --exclude="/\." .

# Evaluate the given command and its arguments (like sudo does)
eval "$@"

# Recurse.
sh $0 "$@"

