#!/usr/bin/sh

# Wait for files to be changed starting on this directory
inotifywait . -e modify move create delete

# Evaluate the given command and its arguments (like sudo does)
eval "$@"

# Recurse.
sh $0 "$@"

